from __future__ import annotations

from copy import deepcopy


CHART_THEME_PRESETS = {
    "light_classic": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#ECEEF6",
        "axes_facecolor": "#ECEEF6",
        "grid_color": "#C9CEDB",
        "wick_color": "#616673",
        "bull_face": "#FFFFFF",
        "bear_face": "#050505",
        "bull_edge": "#B9BBC4",
        "bear_edge": "#050505",
        "zone_demand": "#CED3DE",
        "zone_supply": "#E7BDC4",
        "zone_alpha": 0.65,
        "line_color": "#4A4F5A",
        "bos_color": "#4A4F5A",
        "dotted_color": "#7E8392",
        "price_label_bg": "#050505",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#2C2F37",
        "header_color": "#2B2F39",
    },
    "light_minimal": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F7F7F8",
        "axes_facecolor": "#F7F7F8",
        "grid_color": "#E3E4E8",
        "wick_color": "#50545C",
        "bull_face": "#FFFFFF",
        "bear_face": "#1E1E1E",
        "bull_edge": "#A6ABB7",
        "bear_edge": "#1E1E1E",
        "zone_demand": "#D9DDE7",
        "zone_supply": "#E8D5DB",
        "zone_alpha": 0.55,
        "line_color": "#5D6470",
        "bos_color": "#5D6470",
        "dotted_color": "#959AA7",
        "price_label_bg": "#1E1E1E",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#434850",
        "header_color": "#3A3F47",
    },
    "light_blueprint": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#E9EEF8",
        "axes_facecolor": "#E9EEF8",
        "grid_color": "#C2D0E7",
        "wick_color": "#445675",
        "bull_face": "#FFFFFF",
        "bear_face": "#152238",
        "bull_edge": "#90A6CD",
        "bear_edge": "#152238",
        "zone_demand": "#C9D9F2",
        "zone_supply": "#E5C7D4",
        "zone_alpha": 0.58,
        "line_color": "#3D5378",
        "bos_color": "#3D5378",
        "dotted_color": "#7087B3",
        "price_label_bg": "#152238",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#30415F",
        "header_color": "#263757",
    },
    "dark_tv": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#101010",
        "axes_facecolor": "#101010",
        "grid_color": "#2B2B2B",
        "wick_color": "#F0F0F0",
        "bull_face": "#FFFFFF",
        "bear_face": "#2B2B2B",
        "bull_edge": "#FFFFFF",
        "bear_edge": "#FFFFFF",
        "zone_demand": "#8F8F8F",
        "zone_supply": "#7D7D7D",
        "zone_alpha": 0.22,
        "line_color": "#7BE27B",
        "stop_color": "#FF5A6B",
        "prediction_color": "#F5F5F5",
        "price_label_bg": "#FFFFFF",
        "price_label_fg": "#111111",
        "axis_color": "#EAEAEA",
        "header_color": "#EFEFEF",
        "background_overlay_alpha": 0.42,
    },
    "dark_clean": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#141414",
        "axes_facecolor": "#141414",
        "grid_color": "#2F3135",
        "wick_color": "#EDEDED",
        "bull_face": "#F8F8F8",
        "bear_face": "#202020",
        "bull_edge": "#F8F8F8",
        "bear_edge": "#F8F8F8",
        "zone_demand": "#6E7F75",
        "zone_supply": "#87717A",
        "zone_alpha": 0.2,
        "line_color": "#67D285",
        "stop_color": "#E45F70",
        "prediction_color": "#FFFFFF",
        "price_label_bg": "#F4F4F4",
        "price_label_fg": "#151515",
        "axis_color": "#DCDCDC",
        "header_color": "#F4F4F4",
        "background_overlay_alpha": 0.5,
    },
    "dark_neon": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0A0E14",
        "axes_facecolor": "#0A0E14",
        "grid_color": "#1C2633",
        "wick_color": "#F7FAFF",
        "bull_face": "#FCFEFF",
        "bear_face": "#163343",
        "bull_edge": "#A8F9FF",
        "bear_edge": "#A8F9FF",
        "zone_demand": "#00A86B",
        "zone_supply": "#B35088",
        "zone_alpha": 0.18,
        "line_color": "#5CF2A8",
        "stop_color": "#FF5C8A",
        "prediction_color": "#DCF8FF",
        "price_label_bg": "#DCF8FF",
        "price_label_fg": "#09131D",
        "axis_color": "#D6F5FF",
        "header_color": "#E8FBFF",
        "background_overlay_alpha": 0.56,
    },
    "dark_gold": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#13100B",
        "axes_facecolor": "#13100B",
        "grid_color": "#2D2417",
        "wick_color": "#FBEBD0",
        "bull_face": "#FFF9EB",
        "bear_face": "#3B2D14",
        "bull_edge": "#E8C071",
        "bear_edge": "#E8C071",
        "zone_demand": "#8E6E32",
        "zone_supply": "#8A4B3A",
        "zone_alpha": 0.2,
        "line_color": "#E6C36A",
        "stop_color": "#D96A5E",
        "prediction_color": "#FFF1CE",
        "price_label_bg": "#F8E6B0",
        "price_label_fg": "#1E1608",
        "axis_color": "#F6E2BA",
        "header_color": "#F8E3BB",
        "background_overlay_alpha": 0.55,
    },
    "dark_crimson": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#120D12",
        "axes_facecolor": "#120D12",
        "grid_color": "#2A1C26",
        "wick_color": "#F4E8EF",
        "bull_face": "#FFFFFF",
        "bear_face": "#35192B",
        "bull_edge": "#EAA8C3",
        "bear_edge": "#EAA8C3",
        "zone_demand": "#665065",
        "zone_supply": "#8A4360",
        "zone_alpha": 0.22,
        "line_color": "#FF8FB1",
        "stop_color": "#FF5B7F",
        "prediction_color": "#F8D7E4",
        "price_label_bg": "#FFD8E7",
        "price_label_fg": "#190A12",
        "axis_color": "#F9D9E5",
        "header_color": "#FFDDEB",
        "background_overlay_alpha": 0.58,
    },
    "dark_ocean": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0B1218",
        "axes_facecolor": "#0B1218",
        "grid_color": "#1E313B",
        "wick_color": "#EDF7FA",
        "bull_face": "#FBFEFF",
        "bear_face": "#16343E",
        "bull_edge": "#8FD7E8",
        "bear_edge": "#8FD7E8",
        "zone_demand": "#387C8D",
        "zone_supply": "#5B6D87",
        "zone_alpha": 0.2,
        "line_color": "#69D9EB",
        "stop_color": "#F26D8A",
        "prediction_color": "#E7FBFF",
        "price_label_bg": "#E0F9FF",
        "price_label_fg": "#08141A",
        "axis_color": "#D7F4FB",
        "header_color": "#E6FBFF",
        "background_overlay_alpha": 0.54,
    },
    "light_paper": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F3F0E8",
        "axes_facecolor": "#F3F0E8",
        "grid_color": "#D7D1C5",
        "wick_color": "#585148",
        "bull_face": "#FFFDF7",
        "bear_face": "#1C1A17",
        "bull_edge": "#B4AA9A",
        "bear_edge": "#1C1A17",
        "zone_demand": "#D6D1C7",
        "zone_supply": "#E5CCC8",
        "zone_alpha": 0.58,
        "line_color": "#5B544E",
        "bos_color": "#5B544E",
        "dotted_color": "#8A837A",
        "price_label_bg": "#1C1A17",
        "price_label_fg": "#FFFDF7",
        "axis_color": "#3E3A35",
        "header_color": "#34302B",
    },
    "light_terminal": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#E8F3E8",
        "axes_facecolor": "#E8F3E8",
        "grid_color": "#BCD0BC",
        "wick_color": "#38513C",
        "bull_face": "#F7FFF7",
        "bear_face": "#152116",
        "bull_edge": "#7EA182",
        "bear_edge": "#152116",
        "zone_demand": "#CBDCCB",
        "zone_supply": "#E2CFCF",
        "zone_alpha": 0.56,
        "line_color": "#35563A",
        "bos_color": "#35563A",
        "dotted_color": "#6F9275",
        "price_label_bg": "#152116",
        "price_label_fg": "#F7FFF7",
        "axis_color": "#2F4933",
        "header_color": "#2A4130",
    },
    "light_pastel": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F6EEF3",
        "axes_facecolor": "#F6EEF3",
        "grid_color": "#DECEDD",
        "wick_color": "#635562",
        "bull_face": "#FFFDFF",
        "bear_face": "#241E24",
        "bull_edge": "#C1AFBF",
        "bear_edge": "#241E24",
        "zone_demand": "#D8D6E8",
        "zone_supply": "#E8C8D6",
        "zone_alpha": 0.55,
        "line_color": "#66556A",
        "bos_color": "#66556A",
        "dotted_color": "#9A85A1",
        "price_label_bg": "#241E24",
        "price_label_fg": "#FFFDFF",
        "axis_color": "#514550",
        "header_color": "#4B404A",
    },
    "light_sky": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#E8F0FE",
        "axes_facecolor": "#E8F0FE",
        "grid_color": "#C4D6F5",
        "wick_color": "#3E5A8C",
        "bull_face": "#FFFFFF",
        "bear_face": "#1A2D54",
        "bull_edge": "#8DA8E0",
        "bear_edge": "#1A2D54",
        "zone_demand": "#C5D8F2",
        "zone_supply": "#E2C8D9",
        "zone_alpha": 0.55,
        "line_color": "#3E6AB0",
        "bos_color": "#3E6AB0",
        "dotted_color": "#7A9CD6",
        "price_label_bg": "#1A2D54",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#2C4270",
        "header_color": "#243B66",
    },
    "light_sand": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F5F0E6",
        "axes_facecolor": "#F5F0E6",
        "grid_color": "#DDD3C2",
        "wick_color": "#6B5C4A",
        "bull_face": "#FFFCF8",
        "bear_face": "#2C2218",
        "bull_edge": "#C4B39E",
        "bear_edge": "#2C2218",
        "zone_demand": "#E3DACA",
        "zone_supply": "#E8CDBF",
        "zone_alpha": 0.58,
        "line_color": "#6B563E",
        "bos_color": "#6B563E",
        "dotted_color": "#A38E76",
        "price_label_bg": "#2C2218",
        "price_label_fg": "#FFFCF8",
        "axis_color": "#4A3E2F",
        "header_color": "#3D3326",
    },
    "light_lavender": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F0ECF8",
        "axes_facecolor": "#F0ECF8",
        "grid_color": "#D5CCEA",
        "wick_color": "#4F3F7A",
        "bull_face": "#FFFFFF",
        "bear_face": "#241A44",
        "bull_edge": "#A999CB",
        "bear_edge": "#241A44",
        "zone_demand": "#D4CBF0",
        "zone_supply": "#E6C8DA",
        "zone_alpha": 0.56,
        "line_color": "#5F4A99",
        "bos_color": "#5F4A99",
        "dotted_color": "#8F7ABB",
        "price_label_bg": "#241A44",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#42356E",
        "header_color": "#382D60",
    },
    "light_mint": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#ECF7F2",
        "axes_facecolor": "#ECF7F2",
        "grid_color": "#C8E4D6",
        "wick_color": "#35705A",
        "bull_face": "#FFFFFF",
        "bear_face": "#173A2E",
        "bull_edge": "#7EBAA0",
        "bear_edge": "#173A2E",
        "zone_demand": "#C4E5D6",
        "zone_supply": "#DCCCCE",
        "zone_alpha": 0.56,
        "line_color": "#3E8A6E",
        "bos_color": "#3E8A6E",
        "dotted_color": "#6DB396",
        "price_label_bg": "#173A2E",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#2D6650",
        "header_color": "#255A46",
    },
    "light_coral": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#FCF0EE",
        "axes_facecolor": "#FCF0EE",
        "grid_color": "#EDD5D0",
        "wick_color": "#7A4A42",
        "bull_face": "#FFFFFF",
        "bear_face": "#3A1D18",
        "bull_edge": "#C9A29A",
        "bear_edge": "#3A1D18",
        "zone_demand": "#F0DAD5",
        "zone_supply": "#EDC4C4",
        "zone_alpha": 0.55,
        "line_color": "#A05044",
        "bos_color": "#A05044",
        "dotted_color": "#C48278",
        "price_label_bg": "#3A1D18",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#6E3A30",
        "header_color": "#603228",
    },
    "light_spring": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F2F8E8",
        "axes_facecolor": "#F2F8E8",
        "grid_color": "#D6E8C0",
        "wick_color": "#4E6A3A",
        "bull_face": "#FFFFFF",
        "bear_face": "#1E2E12",
        "bull_edge": "#97BA78",
        "bear_edge": "#1E2E12",
        "zone_demand": "#D4EAC2",
        "zone_supply": "#E6D4C4",
        "zone_alpha": 0.56,
        "line_color": "#58803E",
        "bos_color": "#58803E",
        "dotted_color": "#82AD68",
        "price_label_bg": "#1E2E12",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#3A6028",
        "header_color": "#2F5220",
    },
    "light_rose": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#FDF0F2",
        "axes_facecolor": "#FDF0F2",
        "grid_color": "#F0D5DA",
        "wick_color": "#7A4050",
        "bull_face": "#FFFFFF",
        "bear_face": "#3A1825",
        "bull_edge": "#CF9AAA",
        "bear_edge": "#3A1825",
        "zone_demand": "#F4DAE0",
        "zone_supply": "#F0C8D4",
        "zone_alpha": 0.54,
        "line_color": "#A84A64",
        "bos_color": "#A84A64",
        "dotted_color": "#C77E96",
        "price_label_bg": "#3A1825",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#76324A",
        "header_color": "#662840",
    },
    "light_slate": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#EAECF0",
        "axes_facecolor": "#EAECF0",
        "grid_color": "#C8CCD8",
        "wick_color": "#484D5C",
        "bull_face": "#FFFFFF",
        "bear_face": "#1C1E28",
        "bull_edge": "#969CAE",
        "bear_edge": "#1C1E28",
        "zone_demand": "#D0D4E0",
        "zone_supply": "#E0C8CE",
        "zone_alpha": 0.58,
        "line_color": "#505668",
        "bos_color": "#505668",
        "dotted_color": "#838AA0",
        "price_label_bg": "#1C1E28",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#383C4A",
        "header_color": "#2E3240",
    },
    "dark_matrix": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0C1410",
        "axes_facecolor": "#0C1410",
        "grid_color": "#1A3024",
        "wick_color": "#CCFFCC",
        "bull_face": "#E6FFE6",
        "bear_face": "#14301E",
        "bull_edge": "#66FF99",
        "bear_edge": "#66FF99",
        "zone_demand": "#226644",
        "zone_supply": "#445533",
        "zone_alpha": 0.2,
        "line_color": "#55FF88",
        "stop_color": "#FF4466",
        "prediction_color": "#AAFFCC",
        "price_label_bg": "#88FF99",
        "price_label_fg": "#0C2010",
        "axis_color": "#88EEAA",
        "header_color": "#AAFFBB",
        "background_overlay_alpha": 0.5,
    },
    "dark_amber": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#14100A",
        "axes_facecolor": "#14100A",
        "grid_color": "#2E2418",
        "wick_color": "#FFE0B0",
        "bull_face": "#FFF3D0",
        "bear_face": "#3C2812",
        "bull_edge": "#FFB347",
        "bear_edge": "#FFB347",
        "zone_demand": "#7A5A2A",
        "zone_supply": "#7A4230",
        "zone_alpha": 0.22,
        "line_color": "#FFA826",
        "stop_color": "#E8454A",
        "prediction_color": "#FFD699",
        "price_label_bg": "#FFB84D",
        "price_label_fg": "#1A1208",
        "axis_color": "#E8B86A",
        "header_color": "#F5C878",
        "background_overlay_alpha": 0.52,
    },
    "dark_plasma": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#120C18",
        "axes_facecolor": "#120C18",
        "grid_color": "#281E3C",
        "wick_color": "#E8D0FF",
        "bull_face": "#F8EEFF",
        "bear_face": "#281840",
        "bull_edge": "#C080FF",
        "bear_edge": "#C080FF",
        "zone_demand": "#503878",
        "zone_supply": "#683860",
        "zone_alpha": 0.2,
        "line_color": "#B060FF",
        "stop_color": "#FF4080",
        "prediction_color": "#E0C0FF",
        "price_label_bg": "#C890FF",
        "price_label_fg": "#120820",
        "axis_color": "#C89AFF",
        "header_color": "#D8AAFF",
        "background_overlay_alpha": 0.54,
    },
    "dark_cyber": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0A0E1A",
        "axes_facecolor": "#0A0E1A",
        "grid_color": "#1E2850",
        "wick_color": "#C8DEFF",
        "bull_face": "#E0F0FF",
        "bear_face": "#14204A",
        "bull_edge": "#60B0FF",
        "bear_edge": "#60B0FF",
        "zone_demand": "#204078",
        "zone_supply": "#502858",
        "zone_alpha": 0.2,
        "line_color": "#50A0FF",
        "stop_color": "#FF3068",
        "prediction_color": "#A0D0FF",
        "price_label_bg": "#70B8FF",
        "price_label_fg": "#080C18",
        "axis_color": "#80BAFF",
        "header_color": "#90C8FF",
        "background_overlay_alpha": 0.52,
    },
    "dark_steel": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0E1016",
        "axes_facecolor": "#0E1016",
        "grid_color": "#222838",
        "wick_color": "#E0E4EC",
        "bull_face": "#F4F6FA",
        "bear_face": "#1A202E",
        "bull_edge": "#909AB0",
        "bear_edge": "#909AB0",
        "zone_demand": "#38445C",
        "zone_supply": "#50384C",
        "zone_alpha": 0.2,
        "line_color": "#8899C0",
        "stop_color": "#E06078",
        "prediction_color": "#C8D0E0",
        "price_label_bg": "#98A5C8",
        "price_label_fg": "#0E1018",
        "axis_color": "#A8B4CC",
        "header_color": "#B8C4D8",
        "background_overlay_alpha": 0.5,
    },
    "dark_graphite": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0C0C0C",
        "axes_facecolor": "#0C0C0C",
        "grid_color": "#282828",
        "wick_color": "#E0E0E0",
        "bull_face": "#FFFFFF",
        "bear_face": "#1C1C1C",
        "bull_edge": "#A0A0A0",
        "bear_edge": "#A0A0A0",
        "zone_demand": "#404040",
        "zone_supply": "#503030",
        "zone_alpha": 0.18,
        "line_color": "#C0C0C0",
        "stop_color": "#E05050",
        "prediction_color": "#D0D0D0",
        "price_label_bg": "#CCCCCC",
        "price_label_fg": "#0C0C0C",
        "axis_color": "#B8B8B8",
        "header_color": "#CCCCCC",
        "background_overlay_alpha": 0.48,
    },
    "dark_blood": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#100808",
        "axes_facecolor": "#100808",
        "grid_color": "#281818",
        "wick_color": "#FFD0D0",
        "bull_face": "#FFF0F0",
        "bear_face": "#3C1010",
        "bull_edge": "#E06060",
        "bear_edge": "#E06060",
        "zone_demand": "#602828",
        "zone_supply": "#802828",
        "zone_alpha": 0.2,
        "line_color": "#FF5050",
        "stop_color": "#FF2020",
        "prediction_color": "#F0A0A0",
        "price_label_bg": "#E05050",
        "price_label_fg": "#180808",
        "axis_color": "#D08080",
        "header_color": "#E09090",
        "background_overlay_alpha": 0.5,
    },
    "dark_royal": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0C0A1A",
        "axes_facecolor": "#0C0A1A",
        "grid_color": "#1E1840",
        "wick_color": "#D8D0FF",
        "bull_face": "#F0ECFF",
        "bear_face": "#181040",
        "bull_edge": "#8870E0",
        "bear_edge": "#8870E0",
        "zone_demand": "#302870",
        "zone_supply": "#502860",
        "zone_alpha": 0.2,
        "line_color": "#7860E0",
        "stop_color": "#D04050",
        "prediction_color": "#C0B0F0",
        "price_label_bg": "#8878E8",
        "price_label_fg": "#0C0818",
        "axis_color": "#9080D0",
        "header_color": "#A090D8",
        "background_overlay_alpha": 0.54,
    },
    "dark_emerald": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0A140E",
        "axes_facecolor": "#0A140E",
        "grid_color": "#183022",
        "wick_color": "#C0FFD8",
        "bull_face": "#E0FFEE",
        "bear_face": "#123828",
        "bull_edge": "#50D88A",
        "bear_edge": "#50D88A",
        "zone_demand": "#206040",
        "zone_supply": "#404028",
        "zone_alpha": 0.22,
        "line_color": "#40E880",
        "stop_color": "#E84848",
        "prediction_color": "#90E8B0",
        "price_label_bg": "#60E090",
        "price_label_fg": "#08140A",
        "axis_color": "#70CC90",
        "header_color": "#80DAA0",
        "background_overlay_alpha": 0.5,
    },
    "dark_obsidian": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#080808",
        "axes_facecolor": "#080808",
        "grid_color": "#1A1A1A",
        "wick_color": "#EAEAEA",
        "bull_face": "#FFFFFF",
        "bear_face": "#141414",
        "bull_edge": "#6E6E6E",
        "bear_edge": "#6E6E6E",
        "zone_demand": "#282828",
        "zone_supply": "#3A1C1C",
        "zone_alpha": 0.16,
        "line_color": "#D0D0D0",
        "stop_color": "#E04040",
        "prediction_color": "#B8B8B8",
        "price_label_bg": "#B0B0B0",
        "price_label_fg": "#080808",
        "axis_color": "#A0A0A0",
        "header_color": "#B4B4B4",
        "background_overlay_alpha": 0.44,
    },
    "dark_rust": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#14100C",
        "axes_facecolor": "#14100C",
        "grid_color": "#2E2218",
        "wick_color": "#F0D8C8",
        "bull_face": "#FFECE0",
        "bear_face": "#3C2A1A",
        "bull_edge": "#C08050",
        "bear_edge": "#C08050",
        "zone_demand": "#684428",
        "zone_supply": "#6E3828",
        "zone_alpha": 0.2,
        "line_color": "#E08840",
        "stop_color": "#D04840",
        "prediction_color": "#E8B890",
        "price_label_bg": "#D09050",
        "price_label_fg": "#140E08",
        "axis_color": "#C09068",
        "header_color": "#D0A078",
        "background_overlay_alpha": 0.54,
    },
    "dark_arctic": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0C1018",
        "axes_facecolor": "#0C1018",
        "grid_color": "#1A2640",
        "wick_color": "#D0E8FF",
        "bull_face": "#E8F4FF",
        "bear_face": "#102848",
        "bull_edge": "#6098D8",
        "bear_edge": "#6098D8",
        "zone_demand": "#284A78",
        "zone_supply": "#482848",
        "zone_alpha": 0.22,
        "line_color": "#48A0E8",
        "stop_color": "#E05058",
        "prediction_color": "#80C0F0",
        "price_label_bg": "#60AAE8",
        "price_label_fg": "#080E14",
        "axis_color": "#74ACD8",
        "header_color": "#88BCE0",
        "background_overlay_alpha": 0.52,
    },
    "dark_lava": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#120A08",
        "axes_facecolor": "#120A08",
        "grid_color": "#2E1A10",
        "wick_color": "#FFD0A0",
        "bull_face": "#FFE8C8",
        "bear_face": "#421808",
        "bull_edge": "#E06028",
        "bear_edge": "#E06028",
        "zone_demand": "#703018",
        "zone_supply": "#802018",
        "zone_alpha": 0.2,
        "line_color": "#FF6020",
        "stop_color": "#E03020",
        "prediction_color": "#FFA870",
        "price_label_bg": "#E05830",
        "price_label_fg": "#160A04",
        "axis_color": "#C87850",
        "header_color": "#D88860",
        "background_overlay_alpha": 0.5,
    },
    "dark_purple": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#100C16",
        "axes_facecolor": "#100C16",
        "grid_color": "#221C3A",
        "wick_color": "#DCC8F0",
        "bull_face": "#F0E6FF",
        "bear_face": "#22163E",
        "bull_edge": "#9A6AD0",
        "bear_edge": "#9A6AD0",
        "zone_demand": "#402A6A",
        "zone_supply": "#5A284A",
        "zone_alpha": 0.2,
        "line_color": "#9A50E8",
        "stop_color": "#D0406A",
        "prediction_color": "#C8A0E8",
        "price_label_bg": "#A068E0",
        "price_label_fg": "#0E0814",
        "axis_color": "#A880C8",
        "header_color": "#B890D4",
        "background_overlay_alpha": 0.52,
    },
    "dark_marine": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#080E14",
        "axes_facecolor": "#080E14",
        "grid_color": "#142838",
        "wick_color": "#C0DCE8",
        "bull_face": "#DEF0F8",
        "bear_face": "#0C2038",
        "bull_edge": "#5090A8",
        "bear_edge": "#5090A8",
        "zone_demand": "#1A4A60",
        "zone_supply": "#3A2840",
        "zone_alpha": 0.22,
        "line_color": "#48A8C8",
        "stop_color": "#D84858",
        "prediction_color": "#70C0D8",
        "price_label_bg": "#58A8C0",
        "price_label_fg": "#060C10",
        "axis_color": "#70A0B4",
        "header_color": "#80B0C4",
        "background_overlay_alpha": 0.5,
    },
    "dark_copper": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#12100C",
        "axes_facecolor": "#12100C",
        "grid_color": "#2A2418",
        "wick_color": "#F0DCC8",
        "bull_face": "#FFEEDC",
        "bear_face": "#302618",
        "bull_edge": "#B88058",
        "bear_edge": "#B88058",
        "zone_demand": "#604428",
        "zone_supply": "#603428",
        "zone_alpha": 0.2,
        "line_color": "#D09048",
        "stop_color": "#D04840",
        "prediction_color": "#E0B890",
        "price_label_bg": "#C89060",
        "price_label_fg": "#120E08",
        "axis_color": "#B89070",
        "header_color": "#C8A080",
        "background_overlay_alpha": 0.54,
    },
    "dark_shadow": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#060606",
        "axes_facecolor": "#060606",
        "grid_color": "#141414",
        "wick_color": "#C8C8C8",
        "bull_face": "#F0F0F0",
        "bear_face": "#0C0C0C",
        "bull_edge": "#585858",
        "bear_edge": "#585858",
        "zone_demand": "#202020",
        "zone_supply": "#301818",
        "zone_alpha": 0.14,
        "line_color": "#A0A0A0",
        "stop_color": "#C83030",
        "prediction_color": "#888888",
        "price_label_bg": "#808080",
        "price_label_fg": "#060606",
        "axis_color": "#808080",
        "header_color": "#969696",
        "background_overlay_alpha": 0.4,
    },
    "dark_candy": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#140812",
        "axes_facecolor": "#140812",
        "grid_color": "#301E30",
        "wick_color": "#FFD8F0",
        "bull_face": "#FFF0F8",
        "bear_face": "#3C142E",
        "bull_edge": "#F060A8",
        "bear_edge": "#F060A8",
        "zone_demand": "#602858",
        "zone_supply": "#701838",
        "zone_alpha": 0.2,
        "line_color": "#F048A0",
        "stop_color": "#E83050",
        "prediction_color": "#F898C8",
        "price_label_bg": "#E868A0",
        "price_label_fg": "#140610",
        "axis_color": "#D070A0",
        "header_color": "#E080B0",
        "background_overlay_alpha": 0.52,
    },
    "dark_azure": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0A0E18",
        "axes_facecolor": "#0A0E18",
        "grid_color": "#182040",
        "wick_color": "#C8D8FF",
        "bull_face": "#E0ECFF",
        "bear_face": "#101838",
        "bull_edge": "#6080D8",
        "bear_edge": "#6080D8",
        "zone_demand": "#203868",
        "zone_supply": "#482048",
        "zone_alpha": 0.2,
        "line_color": "#5090F0",
        "stop_color": "#D84858",
        "prediction_color": "#80B0F0",
        "price_label_bg": "#6898E8",
        "price_label_fg": "#080C14",
        "axis_color": "#78A0D8",
        "header_color": "#88B0E0",
        "background_overlay_alpha": 0.52,
    },
    "dark_mocha": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#120E0A",
        "axes_facecolor": "#120E0A",
        "grid_color": "#2A2016",
        "wick_color": "#E8D4BE",
        "bull_face": "#F8ECDA",
        "bear_face": "#2E1E12",
        "bull_edge": "#A0805A",
        "bear_edge": "#A0805A",
        "zone_demand": "#5A4228",
        "zone_supply": "#5A2E22",
        "zone_alpha": 0.2,
        "line_color": "#C8965E",
        "stop_color": "#C84A3E",
        "prediction_color": "#D8B88E",
        "price_label_bg": "#B8906A",
        "price_label_fg": "#100C06",
        "axis_color": "#A88878",
        "header_color": "#B89888",
        "background_overlay_alpha": 0.54,
    },
    "dark_mint": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#08140E",
        "axes_facecolor": "#08140E",
        "grid_color": "#143024",
        "wick_color": "#B0F0D8",
        "bull_face": "#D8FFEE",
        "bear_face": "#0E3426",
        "bull_edge": "#40D8A0",
        "bear_edge": "#40D8A0",
        "zone_demand": "#1A5840",
        "zone_supply": "#382828",
        "zone_alpha": 0.2,
        "line_color": "#38E8A8",
        "stop_color": "#E04058",
        "prediction_color": "#70E0B0",
        "price_label_bg": "#58D8A0",
        "price_label_fg": "#061008",
        "axis_color": "#64BE98",
        "header_color": "#78CEA8",
        "background_overlay_alpha": 0.5,
    },
    "dark_oil": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0A0A08",
        "axes_facecolor": "#0A0A08",
        "grid_color": "#1A1A14",
        "wick_color": "#D8D4C8",
        "bull_face": "#F0ECE0",
        "bear_face": "#181612",
        "bull_edge": "#8A8474",
        "bear_edge": "#8A8474",
        "zone_demand": "#32302A",
        "zone_supply": "#3A201E",
        "zone_alpha": 0.18,
        "line_color": "#B0A890",
        "stop_color": "#C04838",
        "prediction_color": "#B8AE9E",
        "price_label_bg": "#9A9280",
        "price_label_fg": "#080806",
        "axis_color": "#8A8278",
        "header_color": "#9C9488",
        "background_overlay_alpha": 0.46,
    },
}


STYLE_A = CHART_THEME_PRESETS["light_classic"]
STYLE_B = CHART_THEME_PRESETS["dark_tv"]


def infer_style_mode(theme_name: str | None, fallback: str = "B") -> str:
    if not theme_name:
        return fallback
    preset = CHART_THEME_PRESETS.get(theme_name)
    return preset.get("style_mode", fallback) if preset else fallback


def resolve_theme(style_mode: str, theme_name: str | None = None, overrides: dict | None = None) -> dict:
    default_theme = "light_classic" if style_mode == "A" else "dark_tv"
    requested = theme_name or default_theme
    preset = CHART_THEME_PRESETS.get(requested, CHART_THEME_PRESETS[default_theme])
    if preset.get("style_mode") != style_mode:
        preset = CHART_THEME_PRESETS[default_theme]
    theme = deepcopy(preset)
    if overrides:
        theme.update(overrides)
    return theme
