from __future__ import annotations

from copy import deepcopy


# Curated chart themes — clean neutral palettes (dark grey, charcoal, near-black, white, off-white).
# Each preset is professionally tuned: subtle wicks, refined bodies, soft zones, calm accents.

CHART_THEME_PRESETS: dict[str, dict] = {
    # ---------------- LIGHT (Style A) ----------------
    "light_classic": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#FFFFFF",
        "axes_facecolor": "#FFFFFF",
        "grid_color": "#ECEEF1",
        "wick_color": "#6F7682",
        "bull_face": "#FFFFFF",
        "bear_face": "#1B1F26",
        "bull_edge": "#6F7682",
        "bear_edge": "#1B1F26",
        "zone_demand": "#E6EAF0",
        "zone_supply": "#E2D8DA",
        "zone_border_demand": "#B7BFC9",
        "zone_border_supply": "#B69DA2",
        "zone_alpha": 0.55,
        "line_color": "#3D4350",
        "bos_color": "#3D4350",
        "dotted_color": "#7B8290",
        "prediction_color": "#3D4350",
        "stop_color": "#B25460",
        "price_label_bg": "#1B1F26",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#5C6370",
        "header_color": "#22262E",
        "poi_fill": "#9BA3AE",
        "poi_border": "#3D4350",
    },
    "light_pure": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#FFFFFF",
        "axes_facecolor": "#FFFFFF",
        "grid_color": "#F1F2F4",
        "wick_color": "#494E58",
        "bull_face": "#FFFFFF",
        "bear_face": "#0E1014",
        "bull_edge": "#494E58",
        "bear_edge": "#0E1014",
        "zone_demand": "#E8EAEE",
        "zone_supply": "#E6DDDF",
        "zone_border_demand": "#B3B8C0",
        "zone_border_supply": "#B89FA3",
        "zone_alpha": 0.5,
        "line_color": "#2D323B",
        "bos_color": "#2D323B",
        "dotted_color": "#6E7480",
        "prediction_color": "#2D323B",
        "stop_color": "#A94B58",
        "price_label_bg": "#0E1014",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#4A4F58",
        "header_color": "#15181F",
        "poi_fill": "#A6ABB4",
        "poi_border": "#2D323B",
    },
    "light_paper": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F6F6F4",
        "axes_facecolor": "#F6F6F4",
        "grid_color": "#E3E2DD",
        "wick_color": "#5B5C58",
        "bull_face": "#FBFBF8",
        "bear_face": "#1C1D1A",
        "bull_edge": "#5B5C58",
        "bear_edge": "#1C1D1A",
        "zone_demand": "#E1E0DA",
        "zone_supply": "#DFD3D2",
        "zone_border_demand": "#B2B1AA",
        "zone_border_supply": "#A89998",
        "zone_alpha": 0.55,
        "line_color": "#3C3D3A",
        "bos_color": "#3C3D3A",
        "dotted_color": "#7A7B76",
        "prediction_color": "#3C3D3A",
        "stop_color": "#A75864",
        "price_label_bg": "#1C1D1A",
        "price_label_fg": "#FBFBF8",
        "axis_color": "#535350",
        "header_color": "#26261F",
        "poi_fill": "#A6A6A0",
        "poi_border": "#3C3D3A",
    },
    "light_minimal": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#FAFAFB",
        "axes_facecolor": "#FAFAFB",
        "grid_color": "#EEEFF2",
        "wick_color": "#5A5F69",
        "bull_face": "#FFFFFF",
        "bear_face": "#15181E",
        "bull_edge": "#A2A6B0",
        "bear_edge": "#15181E",
        "zone_demand": "#E7E9EE",
        "zone_supply": "#E4DADC",
        "zone_border_demand": "#B6BAC3",
        "zone_border_supply": "#B49DA1",
        "zone_alpha": 0.5,
        "line_color": "#3A3F49",
        "bos_color": "#3A3F49",
        "dotted_color": "#787E89",
        "prediction_color": "#3A3F49",
        "stop_color": "#B25460",
        "price_label_bg": "#15181E",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#4D525B",
        "header_color": "#1F232B",
        "poi_fill": "#9FA3AC",
        "poi_border": "#3A3F49",
    },
    "light_slate": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#EDEFF3",
        "axes_facecolor": "#EDEFF3",
        "grid_color": "#D8DBE2",
        "wick_color": "#535862",
        "bull_face": "#F8FAFC",
        "bear_face": "#171A20",
        "bull_edge": "#878D98",
        "bear_edge": "#171A20",
        "zone_demand": "#D9DDE4",
        "zone_supply": "#DECBCE",
        "zone_border_demand": "#A6ABB5",
        "zone_border_supply": "#A88E92",
        "zone_alpha": 0.55,
        "line_color": "#383D47",
        "bos_color": "#383D47",
        "dotted_color": "#737984",
        "prediction_color": "#383D47",
        "stop_color": "#A8525E",
        "price_label_bg": "#171A20",
        "price_label_fg": "#F8FAFC",
        "axis_color": "#4A4F59",
        "header_color": "#1F242C",
        "poi_fill": "#9DA2AC",
        "poi_border": "#383D47",
    },
    "light_steel": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#F2F3F5",
        "axes_facecolor": "#F2F3F5",
        "grid_color": "#DEE0E4",
        "wick_color": "#4F545E",
        "bull_face": "#FFFFFF",
        "bear_face": "#181B22",
        "bull_edge": "#7E838E",
        "bear_edge": "#181B22",
        "zone_demand": "#DDE0E6",
        "zone_supply": "#DCCFD2",
        "zone_border_demand": "#A4AAB3",
        "zone_border_supply": "#A49093",
        "zone_alpha": 0.55,
        "line_color": "#363B45",
        "bos_color": "#363B45",
        "dotted_color": "#6F757F",
        "prediction_color": "#363B45",
        "stop_color": "#A55260",
        "price_label_bg": "#181B22",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#474C56",
        "header_color": "#1C2028",
        "poi_fill": "#9CA1AB",
        "poi_border": "#363B45",
    },
    "light_dove": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#EFF0F1",
        "axes_facecolor": "#EFF0F1",
        "grid_color": "#DCDDE0",
        "wick_color": "#525660",
        "bull_face": "#FAFAFB",
        "bear_face": "#16181D",
        "bull_edge": "#83878F",
        "bear_edge": "#16181D",
        "zone_demand": "#DCDDE0",
        "zone_supply": "#DACBCD",
        "zone_border_demand": "#A8AAB0",
        "zone_border_supply": "#A48E91",
        "zone_alpha": 0.55,
        "line_color": "#383B44",
        "bos_color": "#383B44",
        "dotted_color": "#71747E",
        "prediction_color": "#383B44",
        "stop_color": "#A85462",
        "price_label_bg": "#16181D",
        "price_label_fg": "#FAFAFB",
        "axis_color": "#494C55",
        "header_color": "#1B1D24",
        "poi_fill": "#9C9FA8",
        "poi_border": "#383B44",
    },
    "light_porcelain": {
        "style_mode": "A",
        "figure_size": (12.8, 7.2),
        "facecolor": "#FCFCFD",
        "axes_facecolor": "#FCFCFD",
        "grid_color": "#E8E9EC",
        "wick_color": "#525762",
        "bull_face": "#FFFFFF",
        "bear_face": "#11141B",
        "bull_edge": "#828892",
        "bear_edge": "#11141B",
        "zone_demand": "#E4E6EA",
        "zone_supply": "#E2D3D6",
        "zone_border_demand": "#ADB1BA",
        "zone_border_supply": "#A99195",
        "zone_alpha": 0.5,
        "line_color": "#2F3540",
        "bos_color": "#2F3540",
        "dotted_color": "#6B7280",
        "prediction_color": "#2F3540",
        "stop_color": "#A55260",
        "price_label_bg": "#11141B",
        "price_label_fg": "#FFFFFF",
        "axis_color": "#454A55",
        "header_color": "#171B23",
        "poi_fill": "#9DA2AD",
        "poi_border": "#2F3540",
    },

    # ---------------- DARK (Style B) ----------------
    "dark_tv": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#131722",
        "axes_facecolor": "#131722",
        "grid_color": "#1F2330",
        "wick_color": "#D1D4DC",
        "bull_face": "#E0E3EB",
        "bear_face": "#1B2030",
        "bull_edge": "#D1D4DC",
        "bear_edge": "#D1D4DC",
        "zone_demand": "#252C3D",
        "zone_supply": "#3A2A33",
        "zone_border_demand": "#3D475E",
        "zone_border_supply": "#5C3F47",
        "zone_alpha": 0.55,
        "line_color": "#4FBF7A",
        "stop_color": "#E5677A",
        "prediction_color": "#E8EAF0",
        "price_label_bg": "#E0E3EB",
        "price_label_fg": "#131722",
        "axis_color": "#9098A8",
        "header_color": "#D1D4DC",
        "poi_fill": "#3A4358",
        "poi_border": "#6C7388",
        "background_overlay_alpha": 0.55,
    },
    "dark_clean": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#15171C",
        "axes_facecolor": "#15171C",
        "grid_color": "#21242C",
        "wick_color": "#D5D7DC",
        "bull_face": "#E5E7EC",
        "bear_face": "#1E2128",
        "bull_edge": "#D5D7DC",
        "bear_edge": "#D5D7DC",
        "zone_demand": "#252830",
        "zone_supply": "#322830",
        "zone_border_demand": "#3A3E48",
        "zone_border_supply": "#523C45",
        "zone_alpha": 0.55,
        "line_color": "#62C988",
        "stop_color": "#E07181",
        "prediction_color": "#ECEDF1",
        "price_label_bg": "#E5E7EC",
        "price_label_fg": "#15171C",
        "axis_color": "#9499A3",
        "header_color": "#D5D7DC",
        "poi_fill": "#383B46",
        "poi_border": "#6B7180",
        "background_overlay_alpha": 0.58,
    },
    "dark_graphite": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#181A1F",
        "axes_facecolor": "#181A1F",
        "grid_color": "#22252C",
        "wick_color": "#CFD2D7",
        "bull_face": "#DFE2E7",
        "bear_face": "#1F2229",
        "bull_edge": "#CFD2D7",
        "bear_edge": "#CFD2D7",
        "zone_demand": "#26292F",
        "zone_supply": "#33282D",
        "zone_border_demand": "#3D4048",
        "zone_border_supply": "#523C42",
        "zone_alpha": 0.55,
        "line_color": "#5DC983",
        "stop_color": "#DE6878",
        "prediction_color": "#E6E8ED",
        "price_label_bg": "#DFE2E7",
        "price_label_fg": "#181A1F",
        "axis_color": "#90949D",
        "header_color": "#CFD2D7",
        "poi_fill": "#383B43",
        "poi_border": "#6A6F7C",
        "background_overlay_alpha": 0.55,
    },
    "dark_charcoal": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#101216",
        "axes_facecolor": "#101216",
        "grid_color": "#1B1E24",
        "wick_color": "#C8CBD0",
        "bull_face": "#D8DBE0",
        "bear_face": "#181B21",
        "bull_edge": "#C8CBD0",
        "bear_edge": "#C8CBD0",
        "zone_demand": "#1F2228",
        "zone_supply": "#2C2127",
        "zone_border_demand": "#343843",
        "zone_border_supply": "#4A363E",
        "zone_alpha": 0.55,
        "line_color": "#5BC580",
        "stop_color": "#DC6676",
        "prediction_color": "#E3E5EA",
        "price_label_bg": "#D8DBE0",
        "price_label_fg": "#101216",
        "axis_color": "#888D97",
        "header_color": "#C8CBD0",
        "poi_fill": "#32353E",
        "poi_border": "#5F6471",
        "background_overlay_alpha": 0.5,
    },
    "dark_obsidian": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0A0B0E",
        "axes_facecolor": "#0A0B0E",
        "grid_color": "#15171B",
        "wick_color": "#C0C3C8",
        "bull_face": "#D3D5DA",
        "bear_face": "#13151A",
        "bull_edge": "#C0C3C8",
        "bear_edge": "#C0C3C8",
        "zone_demand": "#181B20",
        "zone_supply": "#231A1F",
        "zone_border_demand": "#2A2E38",
        "zone_border_supply": "#3F2D34",
        "zone_alpha": 0.55,
        "line_color": "#54C078",
        "stop_color": "#D86372",
        "prediction_color": "#DEE0E5",
        "price_label_bg": "#D3D5DA",
        "price_label_fg": "#0A0B0E",
        "axis_color": "#7F848E",
        "header_color": "#C0C3C8",
        "poi_fill": "#2A2D35",
        "poi_border": "#565B68",
        "background_overlay_alpha": 0.46,
    },
    "dark_carbon": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#16181D",
        "axes_facecolor": "#16181D",
        "grid_color": "#1F2128",
        "wick_color": "#CACDD2",
        "bull_face": "#DCDEE3",
        "bear_face": "#1C1F25",
        "bull_edge": "#CACDD2",
        "bear_edge": "#CACDD2",
        "zone_demand": "#23262D",
        "zone_supply": "#2F242A",
        "zone_border_demand": "#363944",
        "zone_border_supply": "#4D3940",
        "zone_alpha": 0.55,
        "line_color": "#56C57B",
        "stop_color": "#DB6573",
        "prediction_color": "#E1E3E8",
        "price_label_bg": "#DCDEE3",
        "price_label_fg": "#16181D",
        "axis_color": "#8C909A",
        "header_color": "#CACDD2",
        "poi_fill": "#363943",
        "poi_border": "#666B78",
        "background_overlay_alpha": 0.54,
    },
    "dark_iron": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#1C1F25",
        "axes_facecolor": "#1C1F25",
        "grid_color": "#262A32",
        "wick_color": "#D1D4D9",
        "bull_face": "#E2E5EA",
        "bear_face": "#23262E",
        "bull_edge": "#D1D4D9",
        "bear_edge": "#D1D4D9",
        "zone_demand": "#292D35",
        "zone_supply": "#352A31",
        "zone_border_demand": "#3E424D",
        "zone_border_supply": "#553F47",
        "zone_alpha": 0.55,
        "line_color": "#5CC882",
        "stop_color": "#DE6776",
        "prediction_color": "#E5E7EC",
        "price_label_bg": "#E2E5EA",
        "price_label_fg": "#1C1F25",
        "axis_color": "#9398A3",
        "header_color": "#D1D4D9",
        "poi_fill": "#3A3E48",
        "poi_border": "#6E7480",
        "background_overlay_alpha": 0.55,
    },
    "dark_slate": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#171A20",
        "axes_facecolor": "#171A20",
        "grid_color": "#23272F",
        "wick_color": "#CDD0D6",
        "bull_face": "#DFE1E7",
        "bear_face": "#1F232B",
        "bull_edge": "#CDD0D6",
        "bear_edge": "#CDD0D6",
        "zone_demand": "#272B33",
        "zone_supply": "#34272F",
        "zone_border_demand": "#3B4049",
        "zone_border_supply": "#523B44",
        "zone_alpha": 0.55,
        "line_color": "#58C780",
        "stop_color": "#DD6675",
        "prediction_color": "#E3E5EA",
        "price_label_bg": "#DFE1E7",
        "price_label_fg": "#171A20",
        "axis_color": "#8F94A0",
        "header_color": "#CDD0D6",
        "poi_fill": "#383D47",
        "poi_border": "#6A6F7C",
        "background_overlay_alpha": 0.55,
    },
    "dark_shadow": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0D0E11",
        "axes_facecolor": "#0D0E11",
        "grid_color": "#181A1F",
        "wick_color": "#C4C7CC",
        "bull_face": "#D7D9DE",
        "bear_face": "#16181E",
        "bull_edge": "#C4C7CC",
        "bear_edge": "#C4C7CC",
        "zone_demand": "#1C1F25",
        "zone_supply": "#2A1F25",
        "zone_border_demand": "#2E323C",
        "zone_border_supply": "#46333A",
        "zone_alpha": 0.55,
        "line_color": "#52BD77",
        "stop_color": "#D86270",
        "prediction_color": "#DCDFE4",
        "price_label_bg": "#D7D9DE",
        "price_label_fg": "#0D0E11",
        "axis_color": "#80858F",
        "header_color": "#C4C7CC",
        "poi_fill": "#2C3038",
        "poi_border": "#585D69",
        "background_overlay_alpha": 0.48,
    },
    "dark_steel": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#1A1D23",
        "axes_facecolor": "#1A1D23",
        "grid_color": "#252930",
        "wick_color": "#D0D3D8",
        "bull_face": "#E2E4E9",
        "bear_face": "#21242C",
        "bull_edge": "#D0D3D8",
        "bear_edge": "#D0D3D8",
        "zone_demand": "#272B33",
        "zone_supply": "#34282F",
        "zone_border_demand": "#3D424C",
        "zone_border_supply": "#553D46",
        "zone_alpha": 0.55,
        "line_color": "#5AC781",
        "stop_color": "#DD6776",
        "prediction_color": "#E4E6EB",
        "price_label_bg": "#E2E4E9",
        "price_label_fg": "#1A1D23",
        "axis_color": "#9197A2",
        "header_color": "#D0D3D8",
        "poi_fill": "#383D47",
        "poi_border": "#6C7280",
        "background_overlay_alpha": 0.55,
    },
    "dark_smoke": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#1F2228",
        "axes_facecolor": "#1F2228",
        "grid_color": "#292C34",
        "wick_color": "#D5D8DD",
        "bull_face": "#E5E7EC",
        "bear_face": "#262931",
        "bull_edge": "#D5D8DD",
        "bear_edge": "#D5D8DD",
        "zone_demand": "#2D3139",
        "zone_supply": "#382A32",
        "zone_border_demand": "#42464F",
        "zone_border_supply": "#583D46",
        "zone_alpha": 0.55,
        "line_color": "#5DC983",
        "stop_color": "#DE6877",
        "prediction_color": "#E7E9EE",
        "price_label_bg": "#E5E7EC",
        "price_label_fg": "#1F2228",
        "axis_color": "#959BA5",
        "header_color": "#D5D8DD",
        "poi_fill": "#3C4049",
        "poi_border": "#727885",
        "background_overlay_alpha": 0.58,
    },
    "dark_midnight": {
        "style_mode": "B",
        "figure_size": (16, 9),
        "facecolor": "#0E1015",
        "axes_facecolor": "#0E1015",
        "grid_color": "#191B22",
        "wick_color": "#C9CCD1",
        "bull_face": "#DCDFE4",
        "bear_face": "#15181F",
        "bull_edge": "#C9CCD1",
        "bear_edge": "#C9CCD1",
        "zone_demand": "#1E2128",
        "zone_supply": "#2A1F26",
        "zone_border_demand": "#30333D",
        "zone_border_supply": "#46323A",
        "zone_alpha": 0.55,
        "line_color": "#55BF7A",
        "stop_color": "#DA6371",
        "prediction_color": "#E0E2E7",
        "price_label_bg": "#DCDFE4",
        "price_label_fg": "#0E1015",
        "axis_color": "#82878F",
        "header_color": "#C9CCD1",
        "poi_fill": "#2D3139",
        "poi_border": "#5B606C",
        "background_overlay_alpha": 0.48,
    },
}


# Backward-compatible aliases — pointing to the closest curated palette.
_ALIASES = {
    "light_blueprint": "light_slate",
    "light_terminal": "light_classic",
    "light_pastel": "light_dove",
    "light_sky": "light_slate",
    "light_sand": "light_paper",
    "light_lavender": "light_porcelain",
    "light_mint": "light_minimal",
    "light_coral": "light_paper",
    "light_spring": "light_minimal",
    "light_rose": "light_dove",
    "dark_neon": "dark_carbon",
    "dark_gold": "dark_steel",
    "dark_crimson": "dark_charcoal",
    "dark_ocean": "dark_slate",
    "dark_matrix": "dark_graphite",
    "dark_amber": "dark_steel",
    "dark_plasma": "dark_charcoal",
    "dark_cyber": "dark_slate",
    "dark_blood": "dark_obsidian",
    "dark_royal": "dark_carbon",
    "dark_emerald": "dark_iron",
    "dark_rust": "dark_steel",
    "dark_arctic": "dark_slate",
    "dark_lava": "dark_charcoal",
    "dark_purple": "dark_carbon",
    "dark_marine": "dark_slate",
    "dark_copper": "dark_steel",
    "dark_candy": "dark_smoke",
    "dark_azure": "dark_slate",
    "dark_mocha": "dark_carbon",
    "dark_mint": "dark_iron",
    "dark_oil": "dark_charcoal",
}

for _alias, _target in _ALIASES.items():
    if _target in CHART_THEME_PRESETS:
        CHART_THEME_PRESETS[_alias] = deepcopy(CHART_THEME_PRESETS[_target])


STYLE_A = CHART_THEME_PRESETS["light_classic"]
STYLE_B = CHART_THEME_PRESETS["dark_tv"]


def infer_style_mode(theme_name: str | None, fallback: str = "B") -> str:
    if not theme_name:
        return fallback
    preset = CHART_THEME_PRESETS.get(theme_name)
    return preset.get("style_mode", fallback) if preset else fallback


def resolve_theme(style_mode: str, theme_name: str | None = None, overrides: dict | None = None) -> dict:
    default_theme = "light_classic" if style_mode == "A" else "dark_tv"
    requested = theme_name or default_theme
    preset = CHART_THEME_PRESETS.get(requested, CHART_THEME_PRESETS[default_theme])
    if preset.get("style_mode") != style_mode:
        preset = CHART_THEME_PRESETS[default_theme]
    theme = deepcopy(preset)
    if overrides:
        theme.update(overrides)
    return theme
